articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

# www.domain.com/articles/_________
urlpatterns = [
    path('', views.index, name='index'), # articles:index
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'), # variable routing
]

myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # 메타 클래스(데이터를 위한 데이터)
    class Meta:
        ordering = ('-pk',) # 마지막 생성된 것이 가장 첫번째 오도록

    def __self__(self):
        return f'{self.pk} - {self.title}'

articles/forms.py
from django import forms


# 사용자에게 입력받는 field 만 작성
class ArticleForm(forms.Form):
    title = forms.CharField(
        max_length=20,
        label='제목',
        widget=forms.TextInput(
            attrs={
                'placeholder': '혜련이의 모든 것',
            }
        )
    )

    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'placeholder': '혜련이 얘기 하자!',
                'rows': 5,
                'cols': 50,
            }
        )
    )

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm


# 모든 article 을 보여주는 페이지
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


# GET 으로 들어오면? 생성하는 페이지 rendering
# POST 로 들어오면? 생성하는 로직 수행
def create(request):
    if request.method == 'POST':
        # 사용자의 모든 입력 form 통해 받는다.
        form = ArticleForm(request.POST)
        # 처음 함수처럼 Raw Data 를 바로 꺼내는 것은 위험
        # title = request.POST.get('title') (위험)
        # content = request.POST.get('content') (위험)

        # 사용자가 입력한(보낸) 데이터가 유효한지 확인
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            article = Article(title=title, content=content)
            article.save()
            return redirect('articles:index')
        # form.is_valid() 가 False 인 경우
        # valid 하지 않은 값 들어있는 form 을 그대로 담아서 사용자에게 다시 보냄
        # 수정해서 다시 입력하라고!
        # else:
        #     context = {'form': form}
        #     return render(request, 'articles/create.html', context)

    else:  # GET 요청으로 들어왔을 때
        form = ArticleForm()

    # if ~ else~ 동시에 걸리게 indent 앞으로 조정
    context = {'form': form}
    return render(request, 'articles/create.html', context)


def detail(request, article_pk):  # variable routing 이라 두번째 인자 존재
    # 그 번호에 맞는 article 1개만 꺼내서 저장
    article = get_object_or_404(Article, pk=article_pk)
    context = {'article': article}  # 넘김
    return render(request, 'articles/detail.html', context)

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}아티클 생성::Article{% endblock title %}

{% block body %}

<h1>새로운 김혜련 STORY 생성</h1>
<a href="{% url 'articles:index' %}">[BACK]</a>
<hr>
<form action="#" method='POST'>
  {% csrf_token %}
  <!-- name : 보내지는 이름. id는 라벨이 가리키는 곳 의미 -->
  
  {% comment %}
  <label for="title">타이틀: </label><br>
  <input type="text" name='title' id='title'><br> <!-- id 따라 간다 -->
  <label for="content">내용: </label><br>
  <textarea name="content" id="content" cols="30" rows="10"></textarea><br> 
  {% endcomment %}

  <!-- view 함수에서 context = {'form': form} 로 넘기기 때문에 사용 가능 -->
  {{ form.as_p }}

  <button type="submit">생성하기</button>
</form>

{% endblock body %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}아티클::Article{% endblock title %}

{% block body %}

<h1>{{ article.title }}</h1>
<p>{{ article.created_at }}</p>
<hr>
<p>{{ article.content }}</p>
<hr>
<a href="{% url 'articles:index' %}">[BACK]</a>

{% endblock body %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %}아티클::Article{% endblock title %}

{% block body %}

<h1>Articles</h1>
<!-- [NEW] 누르면 이동할 수 있게끔...-->
<a href="{% url 'articles:create' %}">[NEW]</a>
<hr>
{% for article in articles %}
<div>
  <h3>#{{ article.pk }} {{ article.title }}</h3>
  <p>{{ article.created_at }}</p>
  <!-- detail 페이지로 이동할 때 ! primary key 가 있어야 해당 url 로 이동 가능 -->
  <a href="{% url 'articles:detail' article.pk %}">[DETAIL]</a>
</div>
<br>
{% empty %}
<p>아직 게시글이 없읍니다 8ㅅ8</p>
{% endfor %}

{% endblock body %}

myform/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  {% block body %}
  {% endblock body %}
</body>
</html>